Blog/urls.py
from django.urls import path, include
from rest_framework import routers

from .views import *

app_name = 'blog'

router = routers.DefaultRouter()
router.register(r'users', UserListViewSet, basename='users')
router.register(r'posts', PostListViewSet, basename='posts')

urlpatterns = [
    path('', PostList.as_view()),
    path('api/', include(router.urls)),
    path('author/<int:author_id>/', PostListUser.as_view(), name='author_filter'),
    path('create/', PostCreate.as_view(), name='post_create'),
    path('edit/<slug:slug>/', PostEdit.as_view(), name='post_edit'),
    path('<slug:slug>/', PostDetail.as_view(), name='post_detail'),
]

BlogPetProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('Blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

Blog/models.py
import uuid
from datetime import datetime

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _
from tinymce.models import HTMLField

from Blog.fields import WEBPField
from accounts.models import CustomUser


def image_folder(instance, filename):
    return f'posts/title_images/{datetime.now().strftime("%Y/%m/%d")}/{uuid.uuid4().hex}.webp'


def validate_image(image):
    filesize = image.file.size
    megabyte_limit = 5.0
    if filesize > megabyte_limit * 1024 * 1024:
        raise ValidationError("Max file size is %sMB" % str(megabyte_limit))


class Post(models.Model):
    class PostStatus(models.TextChoices):
        PUBLIC = 'PUB', _('Published')
        PRIVATE = 'PRI', _('Private')

    title = models.CharField(max_length=200, unique=True, null=False)
    title_image = WEBPField(upload_to=image_folder, validators=[validate_image], default='posts/home-bg.webp',
                            null=False, verbose_name="Image")
    slug = models.SlugField(max_length=200, unique=True, null=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_posts')
    description = models.TextField(max_length=1000)
    content = HTMLField()

    # updated_date = models.DateTimeField(auto_now=True)
    created_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=3,
        choices=PostStatus.choices,
        default=PostStatus.PUBLIC,
    )

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.title

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.username

accounts/forms.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser


class RegistrationFrom(UserCreationForm):

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    def save(self, commit=True):
        user = super().save(commit=commit)
        if commit:
            auth_user = authenticate(
                username=self.cleaned_data['username'],
                password=self.cleaned_data['password1']
            )
            login(self.request, auth_user)

        return user

    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2']

Blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import QuerySet
from django.http import Http404, HttpResponseNotFound
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views import generic
from rest_framework import viewsets, permissions, generics
from rest_framework.decorators import api_view

import Blog.models
from .models import Post
from django_filters.rest_framework import DjangoFilterBackend
from .serializers import *


class UserListViewSet(viewsets.ModelViewSet):
    queryset = CustomUser.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAdminUser]


class PostListViewSet(viewsets.ModelViewSet):
    class Meta:
        model = models.Post
        fields = ('title_image', 'slug')

    queryset = Post.objects.all().order_by('-created_date')
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['author', 'status']
    serializer_class = PostListSerializer
    permission_classes = [permissions.IsAuthenticated]


class PostList(generic.ListView):
    queryset = \
        Post.objects\
            .filter(status=Post.PostStatus.PUBLIC)\
            .order_by('-created_date')\
            .select_related()\
            .values('title', 'content', 'description', 'author_id', 'author__username', 'created_date', 'slug')
    paginate_by = 5
    template_name = 'post_list.html'


class PostListUser(generic.ListView):
    paginate_by = 5
    template_name = 'post_list_user.html'

    def get_queryset(self):
        queryset = QuerySet
        if self.kwargs['author_id'] is not self.request.user.pk:
            queryset = Post.objects \
                .filter(author=self.kwargs['author_id'], status=Post.PostStatus.PUBLIC) \
                .order_by('-created_date') \
                .select_related() \
                .values('title', 'content', 'description', 'author_id', 'author__username', 'created_date', 'slug', 'status')
        else:
            queryset = Post.objects \
                .filter(author=self.kwargs['author_id']) \
                .order_by('-created_date') \
                .select_related() \
                .values('title', 'content', 'description', 'author_id', 'author__username', 'created_date', 'slug',
                        'status')

        return queryset


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'post_detail.html'

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.status == Blog.models.Post.PostStatus.PRIVATE:
            if obj.author != self.request.user:
                return HttpResponseNotFound("You are not allowed to see this Post")
        return super(PostDetail, self).dispatch(request, args, kwargs)


class PostCreate(LoginRequiredMixin, generic.CreateView):
    model = Post
    template_name = 'post_create.html'
    fields = ['title', 'title_image', 'content', 'description', 'status']

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.slug = slugify(form.instance.title)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:post_detail', kwargs={'slug': self.object.slug})


class PostEdit(LoginRequiredMixin, generic.UpdateView):
    model = Post
    template_name = 'post_edit.html'
    fields = ['title', 'title_image', 'content', 'description', 'status']

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            raise Http404("You are not allowed to edit this Post")
        return super(PostEdit, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        # form.instance.author = self.request.user
        form.instance.slug = slugify(form.instance.title)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:post_detail', kwargs={'slug': self.object.slug})

accounts/views.py
from django.views import generic
from accounts.forms import RegistrationFrom


class SignUpView(generic.CreateView):
    form_class = RegistrationFrom
    success_url = "/"
    template_name = "registration/signup.html"

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        form_kwargs['request'] = self.request
        return form_kwargs

Blog/templates/post_create.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block header_image %}
    background-image: url('{% static "assets/img/home-bg.jpg" %}')
{% endblock header_image %}

{% block header_title %}
    <div class="site-heading">
        <h1>Create a new post</h1>
    </div>
{% endblock header_title %}

{% block Content %}
    <article class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form_errors form type='all' %}

                        {% bootstrap_field form.title %}
                        {% bootstrap_field form.title_image %}
                        {% bootstrap_field form.content %}
                        {% bootstrap_field form.description %}
                        {% bootstrap_field form.status %}

                        {% bootstrap_button button_type="submit" content="OK" %}
                        {% bootstrap_button button_type="reset" content="Cancel" %}
                    </form>
                </div>
            </div>
        </div>
    </article>
    <script type="text/javascript">
        var uploadField = document.getElementById("id_title_image");

        uploadField.onchange = function () {
            if (this.files[0].size > 5242880) {
                alert("Image is too big!");
                this.value = "";
            }
        };
    </script>
{% endblock Content %}

Blog/templates/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block header_image %}
    background-image: url('{{ post.title_image.url }}')
{% endblock header_image %}

{% block header_title %}
    <div class="post-heading">
        <h1>{{ post.title }}</h1>
        <span class="meta">
            Posted by
            <a href="{% url 'blog:author_filter' author_id=post.author_id %}">{{ post.author.username }}</a>
            on {{ post.created_date }}
        </span>
        {% if post.author.username == user.username %}
            <br/>
            <span class="meta">
                <b>
                    <a href="{% url 'blog:post_edit' slug=post.slug %}">EDIT POST</a>
                </b>
            </span>
        {% endif %}
    </div>
{% endblock header_title %}

{% block Content %}
    <article class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {{ post.content | safe }}
                </div>
            </div>
        </div>
    </article>

{% endblock Content %}

Blog/templates/post_edit.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block header_image %}
    background-image: url('{% static "assets/img/home-bg.jpg" %}')
{% endblock header_image %}

{% block header_title %}
    <div class="post-heading">
        <h1>Create a new post</h1>
    </div>
{% endblock header_title %}

{% block Content %}
    <article class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% bootstrap_form_errors form type='all' %}

                        {% bootstrap_field form.title %}
                        {% bootstrap_field form.title_image show_label=False%}
                        {% bootstrap_field form.content %}
                        {% bootstrap_field form.description %}
                        {% bootstrap_field form.status %}

                        {% bootstrap_button button_type="submit" content="OK" %}
                        {% bootstrap_button button_type="reset" content="Cancel" %}
                    </form>
                </div>
            </div>
        </div>
    </article>
    <script type="text/javascript">
        var uploadField = document.getElementById("id_title_image");

        uploadField.onchange = function () {
            if (this.files[0].size > 5242880) {
                alert("Image is too big!");
                this.value = "";
            }
        };
    </script>
{% endblock Content %}

Blog/templates/post_list.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block header_image %}
    background-image: url('{% static "assets/img/home-bg.jpg" %}')
{% endblock header_image %}

{% block header_title %}
    <div class="site-heading">
        <h1>DJANGO BLOG</h1>
        <span class="subheading">Blog made with DJANGO and BOOTSTRAP</span>
    </div>
{% endblock header_title %}

{% block Content %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {% for post in object_list %}
                    <div class="post-preview">
                        <a href="{% url 'blog:post_detail' slug=post.slug %}">
                            <h2 class="post-title">{{ post.title }}</h2>
                            <h3 class="post-subtitle">{{ post.description }}</h3>
                        </a>
                        <p class="post-meta">
                            Posted by
                            <a href="{% url 'blog:author_filter' author_id=post.author_id %}">{{ post.author__username }}</a>
                            on {{ post.created_date }}
                        </p>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4"/>
                {% endfor %}
                {% bootstrap_pagination page_obj url="/?page=1" %}
            </div>
        </div>
    </div>
{% endblock Content %}

Blog/templates/post_list_user.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% block header_image %}
    background-image: url('{% static "assets/img/home-bg.jpg" %}')
{% endblock header_image %}

{% block header_title %}
    <div class="site-heading">
        <h1>DJANGO BLOG</h1>
        <span class="subheading">Blog made with DJANGO and BOOTSTRAP</span>
    </div>
{% endblock header_title %}

{% block Content %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {% for post in object_list %}
                    {% if post.status == 'PRI' and post.author__username == user.username %}
                        <div class="post-preview">
                            <a href="{% url 'blog:post_detail' slug=post.slug %}">
                                <h2 class="post-title">(PRIVATE) {{ post.title }}</h2>
                                <h3 class="post-subtitle">{{ post.description }}</h3>
                            </a>
                            <p class="post-meta">
                                Posted by
                                <a href="{% url 'blog:author_filter' author_id=post.author_id %}">{{ post.author__username }}</a>
                                on {{ post.created_date }}
                            </p>
                        </div>
                        <!-- Divider-->
                        <hr class="my-4"/>
                    {% elif post.status == 'PUB' %}
                        <div class="post-preview">
                            <a href="{% url 'blog:post_detail' slug=post.slug %}">
                                <h2 class="post-title">{{ post.title }}</h2>
                                <h3 class="post-subtitle">{{ post.description }}</h3>
                            </a>
                            <p class="post-meta">
                                Posted by
                                <a href="{% url 'blog:author_filter' author_id=post.author_id %}">{{ post.author__username }}</a>
                                on {{ post.created_date }}
                            </p>
                        </div>
                        <!-- Divider-->
                        <hr class="my-4"/>
                    {% endif %}


                {% endfor %}

                {% bootstrap_pagination page_obj url="?page=1" %}
            </div>
        </div>
    </div>
{% endblock Content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet"
          type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
          rel="stylesheet" type="text/css"/>
    <!-- Bootstrap CSS -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

    <title>DJANGO MVP Blog App</title>
    {{ form.media }}
</head>
<body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="/">DJANGO BLOG</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/">Home</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>

                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link px-lg-3 py-3 py-lg-4" style="text-decoration: underline;"
                           href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-lg-3 py-3 py-lg-4" style="text-decoration: underline;"
                           href="{% url 'signup' %}">Sign-up</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link link-primary px-lg-3 py-3 py-lg-4" style="text-decoration: underline;"
                           href="{% url 'blog:post_create' %}">Create Post</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link link-primary px-lg-3 py-3 py-lg-4" style="text-decoration: underline;"
                           href="{% url 'logout' %}">Logout, {{ user.username }}</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

<!-- Page Header-->
<header class="masthead" style="{% block header_image %}        {% endblock header_image %}">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">

                    {% block header_title %}

                    {% endblock header_title %}

            </div>
        </div>
    </div>
</header>


<!-- Main Content-->

<!-- Post preview-->
{% block Content %}

{% endblock Content %}




<!-- Footer-->
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <img src="{% static 'assets/img/made-with-django.svg' %}" alt=""/>
                    </li>
                </ul>

            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap Bundle with Popper -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>